version: '3'
services:
    poll:
        depends_on:
            - redis
        build: ./poll
        image: pollimage
        ports: 
            - "5000:80"
        restart: always
        networks:
            - poll-tier

    redis:
        image: redis
        expose:
            - "6379"
        restart: always
        networks:
            - poll-tier
            - back-tier
        volumes:
            - db-data:/data

    worker:
        depends_on:
            - redis
            - db
        build: ./worker
        image: workerimage
        restart: always
        environment:
            POSTGRES_PASSWORD: test1
            POSTGRES_USER: test2
            POSTGRES_DB: test3
        networks:
            - back-tier

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: test1
            POSTGRES_USER: test2
            POSTGRES_DB: test3
        networks:
            - result-tier
            - back-tier
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data

    result:
        depends_on:
            - db
        build: ./result
        image: resultimage
        ports:
            - "5001:80"
        restart: always
        environment:
            POSTGRES_PASSWORD: test1
            POSTGRES_USER: test2
            POSTGRES_DB: test3
        networks:
            - result-tier

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data:
